apiVersion: apps/v1
kind: Deployment
metadata:
  name: mybank-api-deployment
  labels:
    app: mybank-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mybank-api
  template:
    metadata:
      labels:
        app: mybank-api
    spec:
      containers:
      - name: mybank-api
        image: 204456373926.dkr.ecr.ap-southeast-1.amazonaws.com/mybank:0a1613c5d40597203990f3871a8ed201edf30dd5
        ports:
        - containerPort: 8080
